### ISSUE TITLE
Don't use remote icon in appdata

### ISSUE THREAD

**Issue by barthalion** [flathub/io.github.vinegarhq.Vinegar#2]
This is not supported on beta.flathub.org which will be released soon, and will become a blocking check on CI.

**Comment by Thelolguy1** [comment]
Hello, what would be an option to implement icons into the flathub page? Ideally we would use the catglass.svg file only on the flathub page, but nowhere else. How can we implement this through the appstream file?

**Comment by Thelolguy1** [comment]
Made a potential PR, will merge.

**Comment by Thelolguy1** [comment]
Solved by #4
