### ISSUE TITLE
Player is not opening after upgrade to 1.5.6 with "panic: assignment to entry in nil map" error

### ISSUE THREAD

**Issue by marcinx64** [flathub/io.github.vinegarhq.Vinegar#62]
Hi I've just recently upgraded Vinegar flatpak version to 1.5.6 and player is not opening anymore.
I've tried reinstalling the app, but this doesn't help.
Full crash log attached.

[vinegar_crashlog.txt](https://github.com/flathub/io.github.vinegarhq.Vinegar/files/13237352/vinegar_crashlog.txt)

**Comment by Thelolguy1** [comment]
Fixed by #63
